Introduction

This analysis will look at games sold from the mid 1980's to the mid 2010's of the current consoles of that time. We will also look at the games sold on the PlayStation 4 to help see the sales of games on just one console, along with IGN's best games.

Here are the areas that will be looked at specifically:

1) Game title
2) Year the game came out
3) Genre of the game
4) How much the game sold in some countries
5) Along with the platform the game is sold on

Applying the libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import chardet

Loading the Data

In [29]:
# reading the first CSV on video game sales from the 1980's to the mid 2010's
platform = pd.read_csv('vgsales.csv')

# displaying the first 5 popular games from the list
platform.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [5]:
with open('PS4_GamesSales.csv', 'rb') as f:
    result = chardet.detect(f.read())
    encoding = result['encoding']
playstation = pd.read_csv('PS4_GamesSales.csv', encoding=encoding)

playstation.head()

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80

In [5]:
with open('ign_bracket_competition.csv', 'rb') as f:
    result = chardet.detect(f.read())
    encoding = result['encoding']
ign = pd.read_csv('ign_bracket_competition.csv', encoding=encoding)

print(ign)

                                      Game  \
0                      Red Dead Redemption
1            Grand Theft Auto: San Andreas
2   Star Wars: Knights of the Old Republic
3                       Fallout: New Vegas
4                        World of Warcraft
..                                     ...
57                      Grand Theft Auto V
58                              Bloodborne
59           Grand Theft Auto: San Andreas
60                      Grand Theft Auto V
61                       God of War (2018)

                                   Opponent  Ratio  Win
0                             Borderlands 2   0.79    1
1                       Mario Kart 8 Deluxe   0.73    1
2                    Tony Hawk Pro Skater 2   0.55    1
3                         League of Legends   0.74    1
4                                  Fortnite   0.62    1
..                                      ...    ...  ...
57                      Batman: Arkham City   0.62    1
58  The Legend of Zelda: Breath of the Wild   0.35    0
59                        God of War (2018)   0.39    0
60  The Legend of Zelda: Breath of the Wild   0.55    1
61                       Grand Theft Auto V   0.62    1

[62 rows x 4 columns]